insert into url (url, title, status_code, check_time) values ('https://foxnews.com/ut/erat/curabitur/gravida.aspx', 'Metoprolol Tartrate and Hydrochlorothiazide', '301', '2017-07-26 14:38:59');
insert into url (url, title, status_code, check_time) values ('https://eventbrite.com/aenean/auctor/gravida.json', 'METHYL SALICYLATE MENTHOL CAPSAICIN', '301', '2017-07-25 23:46:47');
insert into url (url, title, status_code, check_time) values ('http://bloomberg.com/in/eleifend/quam/a/odio/in/hac.html', 'Kit for the Preparation of Technetium Tc 99m Mebrofenin', '301', '2017-07-23 08:16:52');
insert into url (url, title, status_code, check_time) values ('https://vinaora.com/eu/felis/fusce/posuere.png', 'Diltiazem Hydrochloride', '301', '2017-07-24 19:06:55');
insert into url (url, title, status_code, check_time) values ('https://fda.gov/tempor/turpis/nec/euismod/scelerisque.js', 'Metronidazole', '500', '2017-07-26 23:35:38');
insert into url (url, title, status_code, check_time) values ('http://census.gov/augue/vestibulum.html', 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', '404', '2017-07-23 17:39:10');
insert into url (url, title, status_code, check_time) values ('http://examiner.com/et/magnis/dis/parturient/montes/nascetur.html', 'codeine phosphate, guaifenesin and pseudoephedrine hydrochloride', '404', '2017-07-26 05:39:43');
insert into url (url, title, status_code, check_time) values ('http://ft.com/neque/duis/bibendum/morbi/non/quam/nec.html', 'temazepam', '500', '2017-07-26 13:12:32');
insert into url (url, title, status_code, check_time) values ('http://army.mil/amet/eleifend/pede.aspx', 'norethindrone acetate, ethinyl estradiol and ferrous fumarate', '301', '2017-07-25 15:00:44');
insert into url (url, title, status_code, check_time) values ('https://photobucket.com/morbi.png', 'Metoprolol tartrate', '500', '2017-07-23 00:53:50');
insert into url (url, title, status_code, check_time) values ('http://elpais.com/lacinia/aenean/sit/amet/justo/morbi.xml', 'Menthol', '500', '2017-07-25 20:36:45');
insert into url (url, title, status_code, check_time) values ('https://homestead.com/ultrices/enim/lorem/ipsum/dolor.png', 'SODIUM FLUORIDE', '500', '2017-07-24 06:48:27');
insert into url (url, title, status_code, check_time) values ('https://amazon.co.jp/sapien.png', 'Dog Epithelium', '500', '2017-07-24 12:34:15');
insert into url (url, title, status_code, check_time) values ('http://ehow.com/ridiculus/mus/etiam/vel/augue/vestibulum/rutrum.json', 'Atropine Sulfate', '301', '2017-07-26 18:26:28');
insert into url (url, title, status_code, check_time) values ('https://exblog.jp/feugiat/non/pretium/quis/lectus.xml', 'Cefdinir', '500', '2017-07-26 19:09:37');
insert into url (url, title, status_code, check_time) values ('http://instagram.com/blandit/lacinia.html', 'Donepezil Hydrochloride', '301', '2017-07-24 15:11:09');
insert into url (url, title, status_code, check_time) values ('https://shop-pro.jp/volutpat.json', 'benzalkonium chloride', '200', '2017-07-23 13:35:08');
insert into url (url, title, status_code, check_time) values ('http://phoca.cz/dui/proin/leo/odio/porttitor/id.js', 'Bacitracin Zinc and Polymyxin B Sulfate', '301', '2017-07-23 21:50:42');
insert into url (url, title, status_code, check_time) values ('https://pbs.org/quam/turpis/adipiscing.jpg', 'Fluoxetine', '500', '2017-07-23 17:55:16');
insert into url (url, title, status_code, check_time) values ('http://spiegel.de/at/lorem/integer.jpg', 'PETROLATUM', '301', '2017-07-26 21:03:06');
insert into url (url, title, status_code, check_time) values ('http://who.int/molestie/hendrerit/at/vulputate.png', 'Diltiazem hydrochloride', '404', '2017-07-23 17:37:00');
insert into url (url, title, status_code, check_time) values ('https://tuttocitta.it/semper/interdum/mauris/ullamcorper/purus/sit/amet.json', 'Phenylephrine HCl', '301', '2017-07-23 20:28:26');
insert into url (url, title, status_code, check_time) values ('http://xrea.com/vel/pede/morbi.html', 'Benazepril Hydrochloride', '301', '2017-07-25 11:10:15');
insert into url (url, title, status_code, check_time) values ('https://shutterfly.com/duis.html', 'Levetiracetam', '404', '2017-07-26 11:25:48');
insert into url (url, title, status_code, check_time) values ('https://phoca.cz/tortor/duis.json', 'Benzalkonium Chloride, Lidocaine Hydrochloride', '200', '2017-07-26 08:47:43');
insert into url (url, title, status_code, check_time) values ('http://pcworld.com/adipiscing.png', 'Privet', '200', '2017-07-25 14:29:58');
insert into url (url, title, status_code, check_time) values ('http://jugem.jp/amet/sem/fusce/consequat.html', 'phendimetrazine tartrate', '500', '2017-07-24 15:33:51');
insert into url (url, title, status_code, check_time) values ('https://list-manage.com/interdum/mauris/ullamcorper.html', 'Calcium carbonate', '404', '2017-07-24 08:02:57');
insert into url (url, title, status_code, check_time) values ('https://dedecms.com/pede/morbi.jpg', 'coagulation factor ix (recombinant)', '301', '2017-07-24 19:00:46');
insert into url (url, title, status_code, check_time) values ('http://opensource.org/primis/in/faucibus/orci/luctus/et.html', 'aluminum hydroxide, magnesium hydroxide, simethicone', '500', '2017-07-26 14:04:59');
insert into url (url, title, status_code, check_time) values ('http://gravatar.com/nisl/ut/volutpat/sapien/arcu/sed/augue.jsp', 'Arnica Montana, Calendula Officinalis, Symphtym Officinalis, Hypericum Perforatum, Belladonna, Bellis Perennis', '301', '2017-07-25 12:09:54');
insert into url (url, title, status_code, check_time) values ('https://google.nl/vestibulum.js', 'Acetaminophen, Dextromethorphan Hydrobromide, Phenylephrine Hydrochloride', '301', '2017-07-26 03:31:44');
insert into url (url, title, status_code, check_time) values ('http://ebay.co.uk/proin.aspx', 'Benzalkonium Chloride', '301', '2017-07-25 09:30:02');
insert into url (url, title, status_code, check_time) values ('https://cornell.edu/duis/bibendum/morbi/non/quam.js', 'GUINEA PIG EPITHELIA', '301', '2017-07-25 16:58:39');
insert into url (url, title, status_code, check_time) values ('http://mit.edu/in/ante/vestibulum/ante.js', 'Epinastine Hydrochloride', '404', '2017-07-26 11:28:40');
insert into url (url, title, status_code, check_time) values ('https://qq.com/morbi/quis/tortor/id/nulla/ultrices.xml', 'Acetaminophen, Dextromethorphan Hydrobromide, Phenylephrine Hydrochloride', '301', '2017-07-26 17:27:01');
insert into url (url, title, status_code, check_time) values ('http://opensource.org/neque/aenean.html', 'Fluconazole', '301', '2017-07-24 20:44:09');
insert into url (url, title, status_code, check_time) values ('http://gnu.org/condimentum/curabitur.json', 'Zinc Oxide, Ethylhexyl Methoxycinnamate, Benzophenone, Ethylhexyl Salicylate', '404', '2017-07-23 03:55:43');
insert into url (url, title, status_code, check_time) values ('https://google.com.hk/scelerisque/mauris/sit/amet/eros/suspendisse.png', 'azithromycin', '500', '2017-07-25 05:39:43');
insert into url (url, title, status_code, check_time) values ('http://archive.org/at/turpis.jsp', 'Turnip', '200', '2017-07-23 17:38:05');
insert into url (url, title, status_code, check_time) values ('http://howstuffworks.com/sem/sed/sagittis/nam/congue/risus/semper.html', 'Isosorbide Dinitrate', '301', '2017-07-26 14:48:33');
insert into url (url, title, status_code, check_time) values ('https://scientificamerican.com/tristique/in/tempus/sit/amet/sem.aspx', 'Lemon', '500', '2017-07-24 19:54:36');
insert into url (url, title, status_code, check_time) values ('http://multiply.com/phasellus/in/felis/donec.jsp', 'Captopril', '404', '2017-07-24 06:07:01');
insert into url (url, title, status_code, check_time) values ('https://artisteer.com/nam.js', 'Apis Belladonna', '500', '2017-07-25 15:00:41');
insert into url (url, title, status_code, check_time) values ('http://usa.gov/pede/justo.png', 'triamcinolone acetonide', '200', '2017-07-26 23:14:11');
insert into url (url, title, status_code, check_time) values ('http://prweb.com/justo/etiam/pretium/iaculis/justo/in/hac.jpg', 'Minocycline Hydrochloride', '200', '2017-07-25 20:04:10');
insert into url (url, title, status_code, check_time) values ('https://nsw.gov.au/eros.html', 'Simethicone', '200', '2017-07-25 13:11:55');
insert into url (url, title, status_code, check_time) values ('http://163.com/pretium/quis/lectus/suspendisse.js', 'ISOLEUCINE, LEUCINE, LYSINE ACETATE, METHIONINE, PHENYLALANINE, THREONINE, TRYPTOPHAN, VALINE, CYSTEINE HYDROCHLORIDE, HISTIDINE, TYROSINE, N-ACETYL-TYROSINE, ALANINE, ARGININE, PROLINE, SERINE, GLYCINE, ASPARTIC ACID, GLUTAMIC ACID, and TAURINE', '301', '2017-07-25 14:18:02');
insert into url (url, title, status_code, check_time) values ('https://google.ca/quisque/ut/erat/curabitur/gravida/nisi.jpg', 'Acetaminophen, Chlorpheniramine maleate, Phenylephrine HCl', '301', '2017-07-24 10:16:48');
insert into url (url, title, status_code, check_time) values ('https://princeton.edu/diam/neque/vestibulum/eget/vulputate/ut/ultrices.aspx', 'benzoyl peroxide', '200', '2017-07-26 21:23:50');
insert into url (url, title, status_code, check_time) values ('http://geocities.com/praesent/id.jpg', 'LIDOCAINE HYDROCHLORIDE ANHYDROUS', '301', '2017-07-25 04:51:17');
insert into url (url, title, status_code, check_time) values ('http://fc2.com/dictumst/morbi/vestibulum/velit/id/pretium/iaculis.aspx', 'Glycerin', '500', '2017-07-24 15:22:44');
insert into url (url, title, status_code, check_time) values ('http://tinyurl.com/velit/vivamus/vel/nulla/eget/eros/elementum.html', 'MENTHOL', '404', '2017-07-24 02:13:00');
insert into url (url, title, status_code, check_time) values ('http://nba.com/non/lectus/aliquam/sit/amet.png', 'Alendronate Sodium', '500', '2017-07-24 03:30:33');
insert into url (url, title, status_code, check_time) values ('https://statcounter.com/pulvinar/nulla/pede/ullamcorper/augue/a.html', 'Glipizide', '301', '2017-07-24 11:28:40');
insert into url (url, title, status_code, check_time) values ('https://linkedin.com/donec/pharetra/magna/vestibulum/aliquet.aspx', 'Metoprolol succinate', '404', '2017-07-25 21:56:23');
insert into url (url, title, status_code, check_time) values ('https://aboutads.info/at/nulla/suspendisse/potenti/cras/in/purus.aspx', 'Witch Hazel', '500', '2017-07-23 08:43:56');
insert into url (url, title, status_code, check_time) values ('https://typepad.com/orci/eget/orci/vehicula/condimentum.jsp', 'Acetaminophen', '404', '2017-07-23 11:01:08');
insert into url (url, title, status_code, check_time) values ('https://ifeng.com/sapien/in.html', 'Methyl Salicylate', '200', '2017-07-24 18:36:47');
insert into url (url, title, status_code, check_time) values ('http://mapy.cz/proin/at/turpis.aspx', 'Linden', '301', '2017-07-24 18:37:05');
insert into url (url, title, status_code, check_time) values ('https://edublogs.org/donec/ut/dolor.jpg', 'bouteloua gracilis pollen', '301', '2017-07-25 21:26:49');
insert into url (url, title, status_code, check_time) values ('http://telegraph.co.uk/ac/diam/cras/pellentesque/volutpat.js', 'MORELLA CERIFERA ROOT BARK', '500', '2017-07-23 13:04:13');
insert into url (url, title, status_code, check_time) values ('https://uol.com.br/curabitur/convallis/duis/consequat.html', 'Zidovudine', '301', '2017-07-26 09:48:54');
insert into url (url, title, status_code, check_time) values ('https://imdb.com/luctus/rutrum.jpg', 'Divalproex Sodium', '500', '2017-07-25 01:13:26');
insert into url (url, title, status_code, check_time) values ('https://tripod.com/at/dolor/quis.jsp', 'Lidocaine', '500', '2017-07-24 20:52:21');
insert into url (url, title, status_code, check_time) values ('https://ox.ac.uk/et/ultrices/posuere/cubilia/curae/duis.js', 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', '500', '2017-07-23 10:44:47');
insert into url (url, title, status_code, check_time) values ('http://techcrunch.com/dui.aspx', 'Tamsulosin Hydrochloride', '500', '2017-07-24 17:14:32');
insert into url (url, title, status_code, check_time) values ('https://trellian.com/turpis/adipiscing/lorem/vitae/mattis.png', 'Trazodone Hydrochloride', '301', '2017-07-24 13:05:47');
insert into url (url, title, status_code, check_time) values ('http://forbes.com/penatibus/et/magnis/dis/parturient/montes.png', 'TRICLOSAN', '404', '2017-07-25 15:33:13');
insert into url (url, title, status_code, check_time) values ('https://timesonline.co.uk/parturient.png', 'Olanzapine', '301', '2017-07-23 00:23:02');
insert into url (url, title, status_code, check_time) values ('http://imageshack.us/mauris/sit.html', 'Chlorcyclizine Hydrochloride', '301', '2017-07-23 09:30:29');
insert into url (url, title, status_code, check_time) values ('http://wikipedia.org/non/lectus/aliquam.json', 'Miconazole Nitrate', '200', '2017-07-26 00:48:05');
insert into url (url, title, status_code, check_time) values ('https://paypal.com/venenatis/turpis/enim/blandit/mi/in.xml', 'Naproxen Sodium', '301', '2017-07-25 21:01:50');
insert into url (url, title, status_code, check_time) values ('http://fema.gov/turpis/elementum/ligula/vehicula/consequat.xml', 'TRICLOSAN', '500', '2017-07-25 21:11:43');
insert into url (url, title, status_code, check_time) values ('http://ed.gov/a/libero.png', 'Bryonia 30c, Calc Carb 30c, Conium Mac 30c, Helonius 30c, Iodium 30c, Lac Can 30c, Phytolacca 30c, Pulsatilla 30c', '404', '2017-07-23 11:16:54');
insert into url (url, title, status_code, check_time) values ('https://infoseek.co.jp/quis/augue/luctus/tincidunt.json', 'amoxicillin and clavulanate potassium', '301', '2017-07-24 04:53:54');
insert into url (url, title, status_code, check_time) values ('http://yellowpages.com/at/diam/nam/tristique/tortor.jpg', 'Bismuth subsalicylate', '301', '2017-07-25 01:54:40');
insert into url (url, title, status_code, check_time) values ('http://hostgator.com/nullam/sit/amet/turpis/elementum.aspx', 'Whole Grain Barley', '200', '2017-07-23 04:31:59');
insert into url (url, title, status_code, check_time) values ('https://biblegateway.com/ut.xml', 'Clopidogrel bisulfate', '301', '2017-07-24 05:25:55');
insert into url (url, title, status_code, check_time) values ('http://123-reg.co.uk/consequat.xml', 'Levothyroxine Sodium', '500', '2017-07-25 19:10:26');
insert into url (url, title, status_code, check_time) values ('https://sciencedirect.com/ac.xml', 'TRIPROLIDINE HYDROCHLORIDE, PSEUDOEPHEDRINE HYDROCHLORIDE, and DEXTROMETHORPHAN HYDROBROMIDE', '200', '2017-07-23 12:14:24');
insert into url (url, title, status_code, check_time) values ('https://youku.com/sapien/cum/sociis/natoque.jsp', 'Raspberry', '301', '2017-07-23 11:57:58');
insert into url (url, title, status_code, check_time) values ('http://booking.com/felis/sed/interdum/venenatis/turpis/enim/blandit.json', 'DOCUSATE SODIUM', '301', '2017-07-26 09:22:38');
insert into url (url, title, status_code, check_time) values ('https://mapquest.com/pede.json', 'Pine White', '500', '2017-07-24 02:03:07');
insert into url (url, title, status_code, check_time) values ('http://mac.com/fermentum/justo/nec/condimentum/neque.js', 'Hydroxyzine Pamoate', '500', '2017-07-26 03:50:07');
insert into url (url, title, status_code, check_time) values ('http://yellowbook.com/nulla/nisl/nunc/nisl.aspx', 'Ibuprofen', '404', '2017-07-26 11:20:41');
insert into url (url, title, status_code, check_time) values ('https://fema.gov/ultrices/posuere.aspx', 'Glyburide', '500', '2017-07-26 14:30:28');
insert into url (url, title, status_code, check_time) values ('http://free.fr/ante/nulla/justo/aliquam/quis/turpis.jpg', 'Ibuprofen', '301', '2017-07-24 11:38:01');
insert into url (url, title, status_code, check_time) values ('http://wordpress.org/lobortis/sapien/sapien/non.png', 'Buspirone', '301', '2017-07-24 23:58:40');
insert into url (url, title, status_code, check_time) values ('https://google.com.hk/luctus/et/ultrices/posuere/cubilia.jsp', 'Salicylic Acid', '500', '2017-07-23 13:27:52');
insert into url (url, title, status_code, check_time) values ('https://tripod.com/et.js', 'Salicylic Acid', '301', '2017-07-25 14:15:32');
insert into url (url, title, status_code, check_time) values ('http://qq.com/lacus/morbi/sem.jpg', 'Warfarin Sodium', '500', '2017-07-23 20:49:37');
insert into url (url, title, status_code, check_time) values ('http://smugmug.com/ante/ipsum.png', 'Allantoin', '301', '2017-07-24 16:30:47');
insert into url (url, title, status_code, check_time) values ('http://google.nl/nisl/venenatis/lacinia/aenean/sit/amet.xml', 'Olanzapine', '301', '2017-07-26 15:44:46');
insert into url (url, title, status_code, check_time) values ('http://ox.ac.uk/in/libero/ut/massa/volutpat/convallis.json', 'Valproic Acid', '500', '2017-07-24 08:48:04');
insert into url (url, title, status_code, check_time) values ('http://addthis.com/donec.js', 'Citalopram Hydrobromide', '200', '2017-07-23 20:39:15');
insert into url (url, title, status_code, check_time) values ('http://biglobe.ne.jp/felis/eu/sapien.jsp', 'Octinoxate, Oxybenzone, Titanium Dioxide', '301', '2017-07-23 04:35:07');
insert into url (url, title, status_code, check_time) values ('https://issuu.com/nulla/neque/libero/convallis/eget/eleifend/luctus.html', 'Sodium Fluoride', '404', '2017-07-25 09:11:41');
insert into url (url, title, status_code, check_time) values ('http://cnn.com/nibh/in/hac/habitasse/platea/dictumst.html', 'CALCIUM POLYCARBOPHIL', '301', '2017-07-26 15:06:24');
insert into url (url, title, status_code, check_time) values ('https://yahoo.com/proin/risus/praesent/lectus/vestibulum.jpg', 'levothyroxine sodium', '301', '2017-07-26 13:14:59');
insert into url (url, title, status_code, check_time) values ('http://bluehost.com/mauris/eget.jpg', 'GLYCERIN', '200', '2017-07-25 06:17:06');
insert into url (url, title, status_code, check_time) values ('https://wordpress.com/vulputate/vitae/nisl.json', 'Dimethicone', '301', '2017-07-26 05:47:30');
insert into url (url, title, status_code, check_time) values ('https://usa.gov/metus/aenean.html', 'potassium nitrate and sodium fluoride', '404', '2017-07-25 18:54:25');
insert into url (url, title, status_code, check_time) values ('https://cdbaby.com/orci/vehicula/condimentum/curabitur.jsp', 'Dexamethasone sodium phosphate', '301', '2017-07-26 22:28:32');
insert into url (url, title, status_code, check_time) values ('http://cocolog-nifty.com/sapien/placerat.html', 'CEFPROZIL', '404', '2017-07-24 10:10:48');
insert into url (url, title, status_code, check_time) values ('https://sitemeter.com/pellentesque/viverra/pede.jpg', 'dolasetron mesylate', '301', '2017-07-24 20:45:12');
insert into url (url, title, status_code, check_time) values ('http://netscape.com/felis/donec/semper/sapien/a/libero.html', 'Minoxidil', '301', '2017-07-23 18:04:29');
insert into url (url, title, status_code, check_time) values ('https://hubpages.com/molestie/sed/justo/pellentesque/viverra/pede.js', 'rosiglitazone maleate', '200', '2017-07-26 23:30:48');
insert into url (url, title, status_code, check_time) values ('http://google.pl/at.js', 'ACETAMINOPHEN, ASPIRIN, CAFFEINE', '301', '2017-07-26 03:32:37');
insert into url (url, title, status_code, check_time) values ('http://marriott.com/sit.html', 'Norethindrone and Ethinyl Estradiol', '301', '2017-07-26 05:58:52');
insert into url (url, title, status_code, check_time) values ('http://stumbleupon.com/velit.png', 'Doxycycline Hyclate', '301', '2017-07-24 23:30:58');
insert into url (url, title, status_code, check_time) values ('http://cnet.com/in/libero/ut/massa/volutpat.aspx', 'Guaifenesin', '301', '2017-07-23 06:18:03');
insert into url (url, title, status_code, check_time) values ('https://free.fr/luctus/ultricies/eu/nibh/quisque/id/justo.xml', 'Nitrogen', '301', '2017-07-24 22:31:00');
insert into url (url, title, status_code, check_time) values ('https://patch.com/fusce.jsp', 'Xylometazoline HCL', '301', '2017-07-24 23:37:42');
insert into url (url, title, status_code, check_time) values ('https://dyndns.org/diam/nam/tristique/tortor/eu.json', 'Betamethasone Valerate', '301', '2017-07-23 01:36:30');
insert into url (url, title, status_code, check_time) values ('https://goo.gl/vel/augue.jpg', 'Hog Epithelium', '404', '2017-07-25 20:41:50');
insert into url (url, title, status_code, check_time) values ('https://yellowbook.com/mattis/nibh/ligula/nec/sem/duis/aliquam.png', 'Lansoprazole', '404', '2017-07-25 00:40:24');
insert into url (url, title, status_code, check_time) values ('https://stanford.edu/pellentesque/ultrices/phasellus/id/sapien/in/sapien.jpg', 'OCTINOXATE, OXYBENZONE', '404', '2017-07-24 04:15:43');
insert into url (url, title, status_code, check_time) values ('http://engadget.com/lacinia/aenean/sit/amet/justo.aspx', 'Titanium Dioxide, Zinc Oxide', '200', '2017-07-24 00:41:21');
insert into url (url, title, status_code, check_time) values ('http://biblegateway.com/vestibulum/vestibulum/ante/ipsum.jpg', 'Octinoxate 7.5%', '301', '2017-07-25 03:10:51');
insert into url (url, title, status_code, check_time) values ('http://earthlink.net/amet/consectetuer/adipiscing/elit/proin/interdum.aspx', 'ALUMINUM CHLOROHYDRATE', '301', '2017-07-25 22:34:28');
insert into url (url, title, status_code, check_time) values ('https://youtu.be/sollicitudin.png', 'venlafaxine hydrochloride', '301', '2017-07-24 01:37:12');
insert into url (url, title, status_code, check_time) values ('http://google.nl/sem.xml', 'Water', '301', '2017-07-24 09:15:16');
insert into url (url, title, status_code, check_time) values ('http://sakura.ne.jp/justo/sollicitudin/ut/suscipit/a.js', 'Cetirizine HCl, Pseudoephedrine HCl', '301', '2017-07-23 23:33:30');
insert into url (url, title, status_code, check_time) values ('https://mac.com/id/nulla/ultrices/aliquet/maecenas/leo.html', 'SALICYLIC ACID', '200', '2017-07-25 07:54:31');
insert into url (url, title, status_code, check_time) values ('https://mashable.com/vivamus/metus/arcu/adipiscing/molestie/hendrerit/at.html', 'Titanium Dioxide and Zinc Oxide', '301', '2017-07-23 15:28:51');
insert into url (url, title, status_code, check_time) values ('http://walmart.com/odio/cras/mi/pede/malesuada/in/imperdiet.png', 'Cyclobenzaprine Hydrochloride', '301', '2017-07-24 05:32:03');
insert into url (url, title, status_code, check_time) values ('http://hexun.com/pellentesque/volutpat/dui/maecenas.jpg', 'Docusate calcium', '200', '2017-07-25 14:01:36');
insert into url (url, title, status_code, check_time) values ('http://aboutads.info/dapibus/at/diam/nam.html', 'diflorasone diacetate', '301', '2017-07-25 10:23:15');
insert into url (url, title, status_code, check_time) values ('http://cloudflare.com/donec/ut/dolor/morbi/vel/lectus.jpg', 'pantoprazole sodium', '301', '2017-07-24 08:21:48');
insert into url (url, title, status_code, check_time) values ('https://homestead.com/ut/massa/volutpat/convallis/morbi/odio.aspx', 'SODIUM SULFACETAMIDE, SULFUR', '301', '2017-07-23 18:29:18');
insert into url (url, title, status_code, check_time) values ('http://ted.com/velit.xml', 'Berberis Populus', '301', '2017-07-25 11:02:03');
insert into url (url, title, status_code, check_time) values ('https://geocities.jp/amet/sem/fusce/consequat.html', 'Simethicone', '200', '2017-07-26 04:52:30');
insert into url (url, title, status_code, check_time) values ('https://howstuffworks.com/diam/in/magna.js', 'teduglutide', '404', '2017-07-23 18:39:35');
insert into url (url, title, status_code, check_time) values ('http://oakley.com/nulla/integer.json', 'Sheep Sorrel', '301', '2017-07-25 22:39:48');
insert into url (url, title, status_code, check_time) values ('http://surveymonkey.com/sagittis/dui/vel.js', 'HYDROXYUREA', '500', '2017-07-26 15:25:54');
insert into url (url, title, status_code, check_time) values ('http://va.gov/felis/eu/sapien/cursus/vestibulum/proin.jsp', 'Menthol', '301', '2017-07-24 09:16:30');
insert into url (url, title, status_code, check_time) values ('https://icio.us/ac/consequat/metus/sapien/ut/nunc.json', 'Sodium fluoride', '301', '2017-07-24 10:33:59');
insert into url (url, title, status_code, check_time) values ('http://howstuffworks.com/quam/suspendisse/potenti/nullam/porttitor/lacus.aspx', 'DOCUSATE SODIUM', '301', '2017-07-23 09:07:49');
insert into url (url, title, status_code, check_time) values ('http://soundcloud.com/nunc/commodo/placerat/praesent/blandit.js', 'OCTINOXATE, AVOBENZONE', '301', '2017-07-25 09:14:41');
insert into url (url, title, status_code, check_time) values ('https://blinklist.com/viverra.jsp', 'alprazolam', '301', '2017-07-25 13:01:14');
insert into url (url, title, status_code, check_time) values ('http://tiny.cc/montes/nascetur/ridiculus/mus/vivamus/vestibulum/sagittis.png', 'Silicon Dioxide and Calendula Officinalis Flowering Top', '500', '2017-07-24 11:35:40');
insert into url (url, title, status_code, check_time) values ('https://woothemes.com/porttitor/pede/justo/eu/massa.json', 'dimethicone', '200', '2017-07-25 08:52:12');
insert into url (url, title, status_code, check_time) values ('http://huffingtonpost.com/tempus/vel/pede/morbi/porttitor/lorem/id.jsp', 'RISPERIDONE', '301', '2017-07-25 03:53:59');
insert into url (url, title, status_code, check_time) values ('http://cloudflare.com/enim/blandit.html', 'Ethylhexyl Methoxycinnamate, Zinc Oxide', '301', '2017-07-24 12:22:23');
insert into url (url, title, status_code, check_time) values ('http://discovery.com/duis/ac/nibh/fusce.png', 'Wheat Pollen', '500', '2017-07-25 21:37:27');
insert into url (url, title, status_code, check_time) values ('https://infoseek.co.jp/sit/amet/sapien/dignissim.json', 'Acetaminophen, Chlorpheniramine maleate, Phenylephrine HCl', '301', '2017-07-26 08:54:53');
insert into url (url, title, status_code, check_time) values ('https://umich.edu/penatibus/et.aspx', 'Isosorbide Dinitrate', '301', '2017-07-23 03:07:04');
insert into url (url, title, status_code, check_time) values ('http://usatoday.com/vitae/nisi/nam/ultrices/libero.js', 'HYDROQUINONE', '301', '2017-07-26 05:06:14');
insert into url (url, title, status_code, check_time) values ('https://php.net/sapien.html', 'bupropion hydrochloride', '500', '2017-07-24 10:31:35');
insert into url (url, title, status_code, check_time) values ('https://state.tx.us/ut/nulla/sed/accumsan/felis/ut.json', 'DEXTROSE MONOHYDRATE', '301', '2017-07-25 14:01:15');
insert into url (url, title, status_code, check_time) values ('http://sohu.com/quis.aspx', 'Ibuprofen', '301', '2017-07-25 04:13:30');
insert into url (url, title, status_code, check_time) values ('http://bloglovin.com/primis/in/faucibus/orci/luctus/et.json', 'DOCUSATE SODIUM', '500', '2017-07-23 21:28:01');
insert into url (url, title, status_code, check_time) values ('https://howstuffworks.com/in/hac/habitasse/platea/dictumst/etiam/faucibus.js', 'Warfarin Sodium', '404', '2017-07-23 22:58:48');
insert into url (url, title, status_code, check_time) values ('https://harvard.edu/varius/ut/blandit/non.png', 'AVENA SATIVA FLOWERING TOP - CANAKINUMAB - CHAMOMILE - HELLEBORUS NIGER ROOT - MELATONIN - MELISSA OFFICINALIS - PULSATILLA VULGARIS - SEROTONIN - STRYCHNOS IGNATII SEED - SUS SCROFA PINEAL GLAND - VA', '500', '2017-07-25 23:15:26');
insert into url (url, title, status_code, check_time) values ('http://facebook.com/praesent/lectus/vestibulum.json', '3-PHYTASE B (ASPERGILLUS NIGER)', '500', '2017-07-24 11:36:06');
insert into url (url, title, status_code, check_time) values ('http://woothemes.com/mattis/pulvinar/nulla/pede.jpg', 'INFLUENZINUM', '500', '2017-07-24 20:28:20');
insert into url (url, title, status_code, check_time) values ('http://plala.or.jp/nulla/justo/aliquam/quis/turpis.html', 'Triclosan', '301', '2017-07-23 12:45:58');
insert into url (url, title, status_code, check_time) values ('https://engadget.com/eu/sapien/cursus/vestibulum/proin.js', 'Homosalate, Octinoxate, Octisalate, Titanium Dioxide', '500', '2017-07-25 06:05:24');
insert into url (url, title, status_code, check_time) values ('https://ox.ac.uk/libero.jsp', 'Eszopiclone', '500', '2017-07-25 23:22:55');
insert into url (url, title, status_code, check_time) values ('https://about.com/quis/turpis/sed/ante.html', 'Ciprofloxacin Hydrochloride', '404', '2017-07-26 17:58:14');
insert into url (url, title, status_code, check_time) values ('https://cyberchimps.com/interdum.png', 'Loperamide Hydrochloride', '200', '2017-07-25 09:50:38');
insert into url (url, title, status_code, check_time) values ('http://github.com/pellentesque/at/nulla/suspendisse/potenti/cras/in.aspx', 'Nicotine Polacrilex', '404', '2017-07-26 19:52:14');
insert into url (url, title, status_code, check_time) values ('https://ihg.com/non/ligula/pellentesque/ultrices.xml', 'dimethicone, octinoxate, octisalate, oxybenzone', '500', '2017-07-26 08:58:57');
insert into url (url, title, status_code, check_time) values ('https://jimdo.com/pulvinar/nulla/pede/ullamcorper/augue/a.js', 'Octisalate and Octocrylene', '404', '2017-07-26 00:05:30');
insert into url (url, title, status_code, check_time) values ('https://pagesperso-orange.fr/et/ultrices/posuere/cubilia/curae.jpg', 'Elaps corallinus, Adrenalinum, Arsenicum iodatum , Aur. met., Baryta carb., Bryonia, Cactus, Chelidonium majus, Cinchona, Crotalus horridus, Digitalis, Glonoinum, Kali carb., Kali iod ., Lachesis , Naja , Nux vom., Veratrum alb., Vipera berus, Viscum, Ruta, Valeriana', '301', '2017-07-26 08:23:53');
insert into url (url, title, status_code, check_time) values ('http://fc2.com/at.aspx', 'PREDNISONE', '500', '2017-07-24 14:58:53');
insert into url (url, title, status_code, check_time) values ('http://cmu.edu/ut.js', 'OCTINOXATE OXYBENZONE', '200', '2017-07-26 21:04:10');
insert into url (url, title, status_code, check_time) values ('https://nationalgeographic.com/in/quis/justo/maecenas.html', 'atorvastatin calcium', '500', '2017-07-23 14:08:30');
insert into url (url, title, status_code, check_time) values ('https://chron.com/eget/tempus/vel/pede.html', 'Methylprednisolone Acetate', '500', '2017-07-24 22:06:17');
insert into url (url, title, status_code, check_time) values ('http://ebay.com/iaculis.jsp', 'TITANIUM DIOXIDE', '301', '2017-07-23 15:16:46');
insert into url (url, title, status_code, check_time) values ('http://princeton.edu/luctus/et/ultrices/posuere/cubilia/curae/mauris.xml', 'dibasic sodium phosphate, monobasic sodium phosphate', '301', '2017-07-23 20:03:13');
insert into url (url, title, status_code, check_time) values ('http://friendfeed.com/vel/est/donec/odio/justo.html', 'Arizona Cypress', '200', '2017-07-26 18:55:41');
insert into url (url, title, status_code, check_time) values ('https://rakuten.co.jp/amet/diam/in/magna.jsp', 'Thiothixene', '500', '2017-07-26 16:52:12');
insert into url (url, title, status_code, check_time) values ('http://cnet.com/sed/sagittis/nam/congue/risus/semper.jpg', 'Thuja Occidentalis', '500', '2017-07-26 00:58:48');
insert into url (url, title, status_code, check_time) values ('http://seattletimes.com/at/diam/nam/tristique/tortor/eu/pede.json', 'Isopropyl Alcohol', '404', '2017-07-24 05:19:20');
insert into url (url, title, status_code, check_time) values ('http://acquirethisname.com/sit/amet/eros/suspendisse.json', 'Diphenhydramine Hydrochloride', '301', '2017-07-23 04:43:14');
insert into url (url, title, status_code, check_time) values ('http://zimbio.com/pulvinar/sed/nisl.xml', 'AVOBENZONE, OCTISALATE, OCTOCRYLENE', '404', '2017-07-24 07:21:14');
insert into url (url, title, status_code, check_time) values ('https://trellian.com/quisque/ut/erat/curabitur/gravida/nisi.aspx', 'tizanidine', '301', '2017-07-24 06:52:02');
insert into url (url, title, status_code, check_time) values ('http://businessinsider.com/ante/ipsum/primis.jpg', 'Isopropyl alcohol', '301', '2017-07-26 04:05:52');
insert into url (url, title, status_code, check_time) values ('https://usgs.gov/eget.html', 'BENZALKONIUM CHLORIDE', '301', '2017-07-23 20:42:33');
insert into url (url, title, status_code, check_time) values ('http://tripod.com/suscipit.aspx', 'Zinc Oxide', '500', '2017-07-23 22:20:51');
insert into url (url, title, status_code, check_time) values ('https://xrea.com/aliquam/convallis.jpg', 'CAPSICUM OLEORESIN', '500', '2017-07-23 23:37:43');
insert into url (url, title, status_code, check_time) values ('http://globo.com/id/luctus/nec/molestie/sed/justo/pellentesque.jsp', 'ALUMINUM CHLOROHYDRATE', '404', '2017-07-23 01:31:11');
insert into url (url, title, status_code, check_time) values ('http://studiopress.com/volutpat/dui/maecenas/tristique/est/et.js', 'Acetaminophen', '200', '2017-07-24 05:44:18');
insert into url (url, title, status_code, check_time) values ('http://amazonaws.com/nunc/nisl/duis/bibendum/felis.jsp', 'Milk of Magnesia', '301', '2017-07-23 06:49:53');
insert into url (url, title, status_code, check_time) values ('http://lulu.com/erat/vestibulum/sed.xml', 'cephalexin', '200', '2017-07-24 08:36:28');
insert into url (url, title, status_code, check_time) values ('http://ftc.gov/luctus/ultricies/eu/nibh/quisque/id/justo.png', 'Echinacea, Hypericum Perforatum, Symphytum Officinale, Arnica Montana, Agaricus Muscarius, Arsenicum Album, Gelsemium Sempervirens', '404', '2017-07-24 19:14:20');
insert into url (url, title, status_code, check_time) values ('http://usa.gov/sollicitudin.html', 'Alendronate Sodium', '500', '2017-07-26 22:09:32');
insert into url (url, title, status_code, check_time) values ('https://businessinsider.com/posuere/cubilia.xml', 'Clotrimazole', '200', '2017-07-23 20:29:45');
insert into url (url, title, status_code, check_time) values ('http://reverbnation.com/ultrices.jsp', 'Calcium carbonate', '301', '2017-07-23 15:36:42');
insert into url (url, title, status_code, check_time) values ('http://csmonitor.com/ultrices/phasellus.xml', 'Red Mulberry', '301', '2017-07-26 18:39:09');
insert into url (url, title, status_code, check_time) values ('https://a8.net/lacus.json', 'CIPROFLOXACIN HYDROCHLORIDE', '500', '2017-07-23 11:39:33');
insert into url (url, title, status_code, check_time) values ('https://amazon.co.uk/risus/praesent/lectus/vestibulum.jpg', 'metoprolol tartrate', '301', '2017-07-23 20:22:47');
insert into url (url, title, status_code, check_time) values ('http://cam.ac.uk/proin/interdum.jpg', 'Drospirenone and ethinyl estradiol', '301', '2017-07-25 18:21:12');
insert into url (url, title, status_code, check_time) values ('http://addthis.com/rutrum/ac/lobortis/vel.json', 'Titanium Dioxide, Octinoxate', '404', '2017-07-26 06:15:58');
insert into url (url, title, status_code, check_time) values ('https://t-online.de/odio/consequat/varius/integer/ac/leo/pellentesque.aspx', 'OCTINOXATE OCTISALATE OXYBENZONE', '404', '2017-07-24 15:00:46');
insert into url (url, title, status_code, check_time) values ('http://cloudflare.com/nulla/tempus/vivamus/in/felis/eu.jsp', 'HYDROMORPHONE HYDROCHLORIDE', '500', '2017-07-23 20:24:12');
insert into url (url, title, status_code, check_time) values ('http://cdbaby.com/tincidunt/in/leo/maecenas.jpg', 'Avobenzone, Homosalate, Octisalate, Octocrylene, Oxybenzone', '301', '2017-07-24 00:27:00');
insert into url (url, title, status_code, check_time) values ('https://icio.us/primis/in/faucibus/orci/luctus/et/ultrices.json', 'California Mugwort', '301', '2017-07-26 17:52:07');
insert into url (url, title, status_code, check_time) values ('http://cbslocal.com/sem/mauris/laoreet/ut/rhoncus/aliquet.js', 'norethindrone acetate and ethinyl estradiol', '404', '2017-07-23 04:23:41');
insert into url (url, title, status_code, check_time) values ('https://hatena.ne.jp/consequat/dui/nec.html', 'ropinirole', '200', '2017-07-23 14:27:55');
insert into url (url, title, status_code, check_time) values ('https://theguardian.com/risus/semper/porta.jsp', 'ALCOHOL', '500', '2017-07-26 18:38:18');
insert into url (url, title, status_code, check_time) values ('http://shutterfly.com/nunc/commodo/placerat/praesent/blandit.json', 'MIRTAZAPINE', '200', '2017-07-23 01:48:35');
insert into url (url, title, status_code, check_time) values ('http://drupal.org/aliquam/erat/volutpat/in/congue.aspx', 'hydrocortisone', '301', '2017-07-26 01:10:30');
insert into url (url, title, status_code, check_time) values ('http://nymag.com/diam/neque.jsp', 'OCTINOXATE, OCTISALATE, TITANIUM DIOXIDE', '301', '2017-07-26 18:33:34');
insert into url (url, title, status_code, check_time) values ('http://tumblr.com/eget/nunc/donec.aspx', 'Ropinirole', '301', '2017-07-24 19:55:01');
insert into url (url, title, status_code, check_time) values ('https://shutterfly.com/sit/amet/turpis.xml', 'benzonatate', '404', '2017-07-24 13:14:14');
insert into url (url, title, status_code, check_time) values ('http://scientificamerican.com/ultrices/posuere.png', 'Ibuprofen', '301', '2017-07-24 02:48:00');
insert into url (url, title, status_code, check_time) values ('http://oaic.gov.au/aliquam/convallis/nunc.js', 'Triclosan', '301', '2017-07-23 02:01:30');
insert into url (url, title, status_code, check_time) values ('http://hibu.com/curae/nulla/dapibus/dolor.js', 'Acetaminophen, Pamabrom and Pyrilamine maleate', '301', '2017-07-26 18:21:10');
insert into url (url, title, status_code, check_time) values ('https://bloglovin.com/felis/eu/sapien/cursus.aspx', 'Hydralazine Hydrochloride', '301', '2017-07-26 20:52:26');
insert into url (url, title, status_code, check_time) values ('http://theguardian.com/blandit/lacinia/erat/vestibulum/sed/magna.json', 'nifedipine', '301', '2017-07-23 16:29:27');
insert into url (url, title, status_code, check_time) values ('http://npr.org/orci/pede.jsp', 'Fosinopril Sodium', '500', '2017-07-23 22:52:51');
insert into url (url, title, status_code, check_time) values ('https://narod.ru/laoreet/ut/rhoncus/aliquet.jpg', 'zinc acetate and zinc gluconate', '500', '2017-07-24 14:57:20');
insert into url (url, title, status_code, check_time) values ('http://marriott.com/tempus/vivamus/in.png', 'Miconazole nitrate', '404', '2017-07-23 06:09:18');
insert into url (url, title, status_code, check_time) values ('http://wufoo.com/consequat/lectus/in/est/risus/auctor/sed.png', 'GENTAMICIN SULFATE', '301', '2017-07-26 01:25:41');
insert into url (url, title, status_code, check_time) values ('http://qq.com/lorem/vitae/mattis.jsp', 'Dextrose (glucose), Levulose (fructose), Phosphoric Acid', '404', '2017-07-23 17:41:59');
insert into url (url, title, status_code, check_time) values ('https://slideshare.net/sapien/quis/libero/nullam/sit.aspx', 'Clindamycin Palmitate Hydrochloride (Pediatric)', '500', '2017-07-24 13:30:48');
insert into url (url, title, status_code, check_time) values ('http://house.gov/donec.png', 'lamotrigine', '301', '2017-07-24 01:53:44');
insert into url (url, title, status_code, check_time) values ('https://ehow.com/in/magna/bibendum/imperdiet/nullam/orci/pede.jpg', 'telithromycin', '500', '2017-07-25 12:21:49');
insert into url (url, title, status_code, check_time) values ('https://skype.com/hendrerit/at/vulputate/vitae/nisl/aenean.aspx', 'Aralia Quinquefolia, Arnica Montana, Avena Sativa, Carduus Marianus, Dhea, Glandula Suprarenalis Suis, L-Arginine', '301', '2017-07-23 16:30:45');
insert into url (url, title, status_code, check_time) values ('https://wiley.com/tincidunt/lacus/at/velit.aspx', 'Timothy, Standardized', '200', '2017-07-26 02:27:30');
insert into url (url, title, status_code, check_time) values ('http://fc2.com/eleifend.png', 'Atenolol', '200', '2017-07-23 20:02:56');
insert into url (url, title, status_code, check_time) values ('http://mac.com/curae/nulla.aspx', 'Pyrithione Zinc', '301', '2017-07-23 14:53:48');
insert into url (url, title, status_code, check_time) values ('https://shutterfly.com/sed/justo/pellentesque/viverra/pede/ac/diam.png', 'galantamine hydrobromide', '500', '2017-07-24 06:42:07');
insert into url (url, title, status_code, check_time) values ('https://skyrock.com/eu/nibh/quisque/id/justo/sit/amet.html', 'ACTIVATED CHARCOAL, LYCOPODIUM CLAVATUM SPORE, NUTMEG, DAIKON', '404', '2017-07-23 02:11:57');
insert into url (url, title, status_code, check_time) values ('https://ifeng.com/in/hac/habitasse.jsp', 'Guaifenesin, Phenylephrine Hydrochloride', '301', '2017-07-24 11:18:27');
insert into url (url, title, status_code, check_time) values ('https://who.int/in/felis/eu/sapien/cursus/vestibulum/proin.html', 'Titanium Dioxide', '301', '2017-07-24 09:55:33');
insert into url (url, title, status_code, check_time) values ('http://1688.com/tempor/convallis/nulla/neque.jpg', 'PYRITHIONE ZINC', '301', '2017-07-25 02:33:35');
insert into url (url, title, status_code, check_time) values ('http://aboutads.info/volutpat/quam/pede/lobortis/ligula/sit/amet.jpg', 'HYDROMORPHONE HYDROCHLORIDE', '301', '2017-07-23 06:42:40');
insert into url (url, title, status_code, check_time) values ('http://fastcompany.com/viverra/eget.json', 'Avobenzone, Octisalate, Octocrylene, and Oxybenzone', '500', '2017-07-24 03:52:09');
insert into url (url, title, status_code, check_time) values ('https://nifty.com/luctus/cum/sociis/natoque/penatibus/et.aspx', 'Berberis vulgaris, Bladder, Thuja occidentalis, Bryonia, Hepar sulphuris calcareum,', '200', '2017-07-25 10:54:14');
insert into url (url, title, status_code, check_time) values ('https://hud.gov/magnis/dis/parturient/montes/nascetur.png', 'Lamivudine and Zidovudine', '301', '2017-07-24 18:06:45');
insert into url (url, title, status_code, check_time) values ('http://dmoz.org/elit/sodales.aspx', 'Tetracycline Hydrochloride', '301', '2017-07-24 08:02:07');
insert into url (url, title, status_code, check_time) values ('https://cornell.edu/eget/orci/vehicula/condimentum/curabitur.aspx', 'Bisacodyl', '500', '2017-07-24 12:27:05');
insert into url (url, title, status_code, check_time) values ('https://slideshare.net/pretium.js', 'Hydrocodone Bitartrate And Acetaminophen', '200', '2017-07-26 11:38:25');
insert into url (url, title, status_code, check_time) values ('https://dell.com/eu/felis/fusce/posuere.js', 'Titanium Dioxide and Zinc Oxide', '301', '2017-07-26 05:48:54');
insert into url (url, title, status_code, check_time) values ('http://ed.gov/ut/dolor.aspx', 'Octinoxate', '301', '2017-07-25 00:22:04');
insert into url (url, title, status_code, check_time) values ('https://instagram.com/libero.json', 'Hydrochlorothiazide', '301', '2017-07-26 16:25:38');
insert into url (url, title, status_code, check_time) values ('https://dot.gov/vulputate/luctus.xml', 'Clindamycin hydrochloride', '301', '2017-07-24 23:08:36');
insert into url (url, title, status_code, check_time) values ('http://g.co/sapien/varius/ut.jpg', 'Ibuprofen', '404', '2017-07-25 02:43:11');
insert into url (url, title, status_code, check_time) values ('http://businessweek.com/eget/nunc/donec/quis/orci.js', 'homosalate, octisalate, avobenzone, octocrylene', '404', '2017-07-26 18:49:31');
insert into url (url, title, status_code, check_time) values ('https://booking.com/in/sapien/iaculis/congue.aspx', 'Acetaminophen, DEXTROMETHORPHAN HYDROBROMIDE, and DOXYLAMINE SUCCINATE', '200', '2017-07-26 19:35:00');
insert into url (url, title, status_code, check_time) values ('https://acquirethisname.com/nec/euismod/scelerisque.jsp', 'Lisinopril and Hydrochlorothiazide', '301', '2017-07-23 20:38:19');
insert into url (url, title, status_code, check_time) values ('https://stumbleupon.com/quis/odio/consequat/varius/integer.json', 'Nitrogen', '301', '2017-07-26 21:41:57');
insert into url (url, title, status_code, check_time) values ('http://flickr.com/elit/ac/nulla/sed/vel/enim/sit.aspx', 'Rotavirus Vaccine, Live, Oral', '500', '2017-07-24 08:20:01');
insert into url (url, title, status_code, check_time) values ('http://paginegialle.it/vitae/mattis/nibh.png', 'DOXAZOSIN MESYLATE', '404', '2017-07-24 23:09:21');
insert into url (url, title, status_code, check_time) values ('http://nbcnews.com/nisl/aenean/lectus/pellentesque/eget.jpg', 'nicotine', '404', '2017-07-26 04:45:03');
insert into url (url, title, status_code, check_time) values ('https://wix.com/enim.html', 'Dextromethorphan Hydrobromide', '301', '2017-07-24 06:30:54');
insert into url (url, title, status_code, check_time) values ('https://ning.com/erat/fermentum.js', 'Oxygen', '301', '2017-07-26 02:26:14');
insert into url (url, title, status_code, check_time) values ('https://npr.org/sagittis.xml', 'cefuroxime sodium', '301', '2017-07-26 04:00:54');
insert into url (url, title, status_code, check_time) values ('https://mit.edu/pretium/iaculis/diam/erat.png', 'Dextromethorphan HBr, Guaifenesin, Phenylephrine HCl', '301', '2017-07-23 05:59:48');
insert into url (url, title, status_code, check_time) values ('http://globo.com/massa.png', 'tramadol hydrochloride', '301', '2017-07-24 17:06:15');
insert into url (url, title, status_code, check_time) values ('https://devhub.com/in/felis/eu/sapien/cursus.html', 'loratadine', '500', '2017-07-26 11:31:23');
insert into url (url, title, status_code, check_time) values ('http://alibaba.com/convallis/morbi/odio/odio.html', 'Diltiazem Hydrochloride', '200', '2017-07-26 02:53:58');
insert into url (url, title, status_code, check_time) values ('https://nymag.com/ultrices/phasellus/id/sapien.png', 'hydrocortisone acetate and pramoxine hydrochloride', '301', '2017-07-24 15:27:12');
insert into url (url, title, status_code, check_time) values ('http://twitter.com/maecenas/ut/massa.png', 'Berberis vulgaris, Cochlearia armoracia, Echineacea (angustifolia), Hydrastis canadensis, Lomatium dissectum, Myrrha, Tabebuia impetiginosa, Propolis,', '500', '2017-07-25 21:31:06');
insert into url (url, title, status_code, check_time) values ('http://xinhuanet.com/at.jsp', 'Menthol, Capsicum Annum Extract', '500', '2017-07-25 16:13:16');
insert into url (url, title, status_code, check_time) values ('http://upenn.edu/molestie.aspx', 'Magnesium hydroxide', '200', '2017-07-25 00:49:28');
insert into url (url, title, status_code, check_time) values ('http://addtoany.com/nec/condimentum/neque.jsp', 'Octinoxate, Zinc Oxide, Avobenzone', '500', '2017-07-24 21:38:07');
insert into url (url, title, status_code, check_time) values ('http://soup.io/id/ornare.jpg', 'Flutamide', '500', '2017-07-23 05:55:01');
insert into url (url, title, status_code, check_time) values ('http://discuz.net/ipsum.aspx', 'Oxcarbazepine', '200', '2017-07-25 12:17:02');
insert into url (url, title, status_code, check_time) values ('https://imdb.com/odio/elementum/eu/interdum/eu.xml', 'rivaroxaban', '500', '2017-07-23 00:07:52');
insert into url (url, title, status_code, check_time) values ('https://howstuffworks.com/parturient/montes.xml', 'Benzocaine, Resorcinol', '200', '2017-07-25 20:36:58');
insert into url (url, title, status_code, check_time) values ('http://webeden.co.uk/id/nisl/venenatis/lacinia/aenean.jsp', 'HYDROCHLORIC ACID', '301', '2017-07-24 00:49:40');
insert into url (url, title, status_code, check_time) values ('https://nhs.uk/maecenas/leo/odio.js', 'Zinc pyrithione', '200', '2017-07-24 12:59:12');
insert into url (url, title, status_code, check_time) values ('https://cdc.gov/luctus/nec/molestie.json', 'efavirenz, emtricitabine, and tenofovir disoproxil fumarate', '500', '2017-07-24 23:48:17');
insert into url (url, title, status_code, check_time) values ('http://businessinsider.com/nulla.html', 'OCTINOXATE', '301', '2017-07-23 12:05:21');
insert into url (url, title, status_code, check_time) values ('http://lulu.com/augue/a/suscipit/nulla.aspx', 'Diltiazem Hydrochloride', '500', '2017-07-25 04:16:25');
insert into url (url, title, status_code, check_time) values ('http://wikipedia.org/eget/semper/rutrum/nulla.xml', 'Levetiracetam', '500', '2017-07-24 14:29:42');
insert into url (url, title, status_code, check_time) values ('http://hostgator.com/eleifend/donec/ut/dolor/morbi/vel.xml', 'olmesartan medoxomil-hydrochlorothiazide', '301', '2017-07-25 18:33:00');
insert into url (url, title, status_code, check_time) values ('http://people.com.cn/cum/sociis/natoque/penatibus/et.jpg', 'Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone', '301', '2017-07-25 14:20:54');
insert into url (url, title, status_code, check_time) values ('https://walmart.com/nullam/varius/nulla/facilisi/cras/non/velit.js', 'Polyethylene Glycol-3350', '404', '2017-07-26 19:09:50');
insert into url (url, title, status_code, check_time) values ('http://lulu.com/pharetra/magna/ac/consequat/metus/sapien.html', 'Avena sativa, Carduus marianus, Damiana, Galium aparine, Hamamelis virginiana, Hepar bovinum, Korean ginseng, Nuphar luteum, Orchitinum bovinum,', '500', '2017-07-24 05:53:22');
insert into url (url, title, status_code, check_time) values ('https://woothemes.com/tortor/quis/turpis.png', 'Standardized Mite D. pteronyssinus', '404', '2017-07-26 07:09:56');
insert into url (url, title, status_code, check_time) values ('http://google.co.uk/potenti/in/eleifend.jsp', 'BENZALKONIUM CHLORIDE', '200', '2017-07-23 12:10:53');
insert into url (url, title, status_code, check_time) values ('https://mtv.com/blandit/non/interdum/in/ante/vestibulum/ante.png', 'Acetaminophen, Dextromethorphan HBr, Doxylamine succinate', '500', '2017-07-23 22:31:43');
insert into url (url, title, status_code, check_time) values ('http://ox.ac.uk/duis/faucibus/accumsan/odio/curabitur/convallis/duis.html', 'hydrocortisone', '301', '2017-07-26 00:59:03');
insert into url (url, title, status_code, check_time) values ('http://hud.gov/purus/sit/amet.png', 'Benzonatate', '404', '2017-07-24 03:39:25');
insert into url (url, title, status_code, check_time) values ('https://indiatimes.com/morbi/non/lectus/aliquam.aspx', 'THIOSINAMINUM', '500', '2017-07-25 18:55:15');
insert into url (url, title, status_code, check_time) values ('http://baidu.com/ultrices/enim.jpg', 'Isopropyl alcohol', '301', '2017-07-25 17:03:06');
insert into url (url, title, status_code, check_time) values ('https://ucsd.edu/nulla/eget/eros/elementum/pellentesque.png', 'Furosemide', '301', '2017-07-26 05:07:57');
insert into url (url, title, status_code, check_time) values ('http://fotki.com/pharetra/magna/ac.js', 'MAGNESIUM', '200', '2017-07-26 04:08:21');
insert into url (url, title, status_code, check_time) values ('https://newyorker.com/eros/viverra/eget.jpg', 'Cyclobenzaprine Hydrochloride', '301', '2017-07-23 00:13:06');
insert into url (url, title, status_code, check_time) values ('https://blogs.com/praesent/lectus/vestibulum/quam/sapien/varius/ut.aspx', 'PHENYTOIN SODIUM', '301', '2017-07-26 20:36:36');
insert into url (url, title, status_code, check_time) values ('http://patch.com/cubilia/curae/donec/pharetra/magna/vestibulum/aliquet.jsp', 'fentanyl', '301', '2017-07-26 16:59:12');
insert into url (url, title, status_code, check_time) values ('http://walmart.com/nulla/mollis/molestie/lorem/quisque/ut/erat.js', 'Mentha pip, Zingiber, Pulsatilla , Cocculus , Kali phos , Sucrose', '301', '2017-07-24 14:46:40');
insert into url (url, title, status_code, check_time) values ('http://pbs.org/lobortis/vel/dapibus/at/diam.json', 'Lisinopril', '301', '2017-07-23 22:29:52');
insert into url (url, title, status_code, check_time) values ('http://themeforest.net/semper/interdum/mauris/ullamcorper.png', 'Ibuprofen', '301', '2017-07-25 05:53:19');
insert into url (url, title, status_code, check_time) values ('http://aboutads.info/massa/tempor/convallis/nulla/neque/libero/convallis.aspx', 'Salicylic Acid', '301', '2017-07-24 01:32:52');
insert into url (url, title, status_code, check_time) values ('https://phoca.cz/dignissim/vestibulum/vestibulum/ante.html', 'OCTINOXATE, OCTISALATE, OCTOCRYLENE, ENSULIZOLE, TITANIUM DIOXIDE, OXYBENZONE', '301', '2017-07-24 06:54:24');
insert into url (url, title, status_code, check_time) values ('https://nhs.uk/eleifend/pede/libero/quis/orci.aspx', 'ACETAMINOPHEN, DIPHENHYDRAMINE HYDROCHLORIDE, and PHENYLEPHRINE HYDROCHLORIDE', '301', '2017-07-25 01:47:28');
insert into url (url, title, status_code, check_time) values ('http://unicef.org/praesent.xml', 'Acetaminophen', '301', '2017-07-26 01:27:41');
insert into url (url, title, status_code, check_time) values ('https://i2i.jp/et/ultrices/posuere/cubilia/curae.jsp', 'Ethyl Alcohol', '500', '2017-07-25 03:53:53');
insert into url (url, title, status_code, check_time) values ('https://discuz.net/eleifend/donec/ut/dolor/morbi.json', 'Octinoxate and Avobenzone', '301', '2017-07-25 19:09:45');
insert into url (url, title, status_code, check_time) values ('http://indiatimes.com/nulla/justo/aliquam/quis/turpis/eget/elit.jsp', 'dextromethorphan polistirex', '500', '2017-07-25 07:22:54');
insert into url (url, title, status_code, check_time) values ('https://goo.gl/condimentum/neque/sapien/placerat.jsp', 'Polyvinyl Alcohol', '404', '2017-07-26 14:09:31');
insert into url (url, title, status_code, check_time) values ('http://mtv.com/sagittis.png', 'Dextromethorphan, Guiafenesin, Pseudoephedrine HCl', '500', '2017-07-23 17:10:16');
insert into url (url, title, status_code, check_time) values ('http://nymag.com/nisi/eu.aspx', 'Octinoxate and Oxybenzone', '301', '2017-07-24 13:13:18');
